# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/codec_system/codec_system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system || ORIG_REF_NAME==codec_system} -quiet] -quiet

# IP: bd/codec_system/ip/codec_system_Codec_0_0/codec_system_Codec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system_Codec_0_0 || ORIG_REF_NAME==codec_system_Codec_0_0} -quiet] -quiet

# IP: bd/codec_system/ip/codec_system_processing_system7_0_0/codec_system_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system_processing_system7_0_0 || ORIG_REF_NAME==codec_system_processing_system7_0_0} -quiet] -quiet

# IP: bd/codec_system/ip/codec_system_ps7_0_axi_periph_0/codec_system_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system_ps7_0_axi_periph_0 || ORIG_REF_NAME==codec_system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system_rst_ps7_0_100M_0 || ORIG_REF_NAME==codec_system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/codec_system/ip/codec_system_auto_pc_0/codec_system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==codec_system_auto_pc_0 || ORIG_REF_NAME==codec_system_auto_pc_0} -quiet] -quiet

# XDC: bd/codec_system/codec_system_ooc.xdc
