# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0.xci
# IP: The module: 'codec_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0.xci
# IP: The module: 'codec_system_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/Marcin/Vivado/hc_arm/hc_arm.srcs/sources_1/bd/codec_system/ip/codec_system_rst_ps7_0_100M_0/codec_system_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'codec_system_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
